name: CD

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: BetaHuhn/deploy-to-vercel-action@latest
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}} 
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}} 
        PRODUCTION: true