name: CD

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    if: ((github.event.action == 'closed' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: BetaHuhn/deploy-to-vercel-action@latest
      with:
        VERCEL_TOKEN: ${{ secrets.VERCEL_GITHUB_ACTIONS_TOKEN }} 
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}} 
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}} 
        PRODUCTION: true