name: CI

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Test_and_Build:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: ${{ steps.deploy-dev.outputs.PREVIEW_URL }}
    steps:
      - name: Fetch commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      
      - name: Install dependencies  
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run Tests
        run: CI=true pnpm jest --coverage
      
      - name: Generate coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build App
        run: pnpm build

      - name: Deploy App to Development
        id: deploy-dev
        uses: BetaHuhn/deploy-to-vercel-action@latest 
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
          PRODUCTION: false
          GITHUB_DEPLOYMENT_ENV: Development
  
  Storybook:
    runs-on: ubuntu-latest
    environment:
      name: Storybook
      url: ${{ steps.storybook-deploy.outputs.preview-url }}
    steps:
      - name: Fetch commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      
      - name: Install dependencies  
        run: pnpm install --frozen-lockfile

      - name: Build Storybook
        run: pnpm run storybook:build
      
      - name: Deploy Storybook to Development
        id: storybook-deploy
      - uses: amondnet/vercel-action@v20 #deploy
        id: storybook-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}}
          vercel-project-id: ${{ secrets.VERCEL_STORYBOOK_PROJECT_ID}}
      
