name: CD

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    needs: [Test_and_Build]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.app-deploy.outputs.PREVIEW_URL }}
    steps:
      - name: Fetch commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'pnpm'
      
      - name: Install dependencies  
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run Tests
        run: CI=true pnpm jest
      
      - name: Build App
        run: pnpm build
      
      - name: Deploy App to Production
        id: app-deploy
        uses: BetaHuhn/deploy-to-vercel-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}} 
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}} 
          PRODUCTION: true